"""Phase-v1 skill catalog aligned to the valuation workbook contract."""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class SkillSpec:
    """Declarative definition of a skill used by the orchestrator."""

    skill_id: str
    skill_path: str
    phase: str
    purpose: str
    required_tools: tuple[str, ...]
    workbook_tabs: tuple[str, ...]
    named_ranges: tuple[str, ...]


PHASE_V1_SKILLS: tuple[SkillSpec, ...] = (
    SkillSpec(
        skill_id="google-sheets-range-discipline",
        skill_path="skills/google-sheets-range-discipline",
        phase="global",
        purpose=(
            "Enforce strict named-range-only generation for all Google Sheets tool calls."
        ),
        required_tools=("google_sheets",),
        workbook_tabs=(
            "Inputs",
            "Dilution (TSM)",
            "R&D Capitalization",
            "Lease Capitalization",
            "DCF",
            "Sensitivity",
            "Comps",
            "Checks",
            "Sources",
            "Story",
            "Output",
            "Agent Log",
        ),
        named_ranges=(
            "inp_ticker",
            "inp_name",
            "inp_px",
            "inp_rf",
            "inp_erp",
            "inp_beta",
            "calc_ke",
            "calc_wacc",
            "inp_cash",
            "inp_debt",
            "inp_basic_shares",
            "calc_diluted_shares",
            "calc_lease_debt",
            "inp_tsm_tranche1_count_mm",
            "inp_tsm_tranche1_strike",
            "inp_tsm_tranche1_type",
            "inp_tsm_tranche1_note",
            "tsm_tranche_table",
            "out_tsm_incremental_shares",
            "out_tsm_diluted_shares",
            "sens_base_value_ps",
            "sens_wacc_vector",
            "sens_terminal_g_vector",
            "sens_grid_values",
            "sens_grid_full",
            "comps_target_rev_ttm",
            "comps_target_ebit_ttm",
            "comps_header",
            "comps_firstrow",
            "comps_table",
            "comps_table_full",
            "comps_peer_tickers",
            "comps_peer_names",
            "comps_multiples_header",
            "comps_multiples_values",
            "comps_method_note",
            "comps_peer_count",
            "comps_multiple_count",
            "comps_ev_ebit",
            "comps_ev_sales",
            "comps_pe",
            "comps_notes",
            "sources_header",
            "sources_firstrow",
            "sources_table",
            "story_thesis",
            "story_growth",
            "story_profitability",
            "story_reinvestment",
            "story_risk",
            "story_sanity_checks",
            "story_grid_header",
            "story_grid_rows",
            "story_grid_citations",
            "story_memo_hooks",
            "inp_w_pess",
            "inp_w_base",
            "inp_w_opt",
            "inp_pess_g1",
            "inp_pess_g2",
            "inp_pess_g3",
            "inp_pess_g4",
            "inp_pess_g5",
            "inp_pess_m5",
            "inp_pess_m10",
            "inp_pess_tax",
            "inp_pess_wacc",
            "inp_pess_gt",
            "inp_base_g1",
            "inp_base_g2",
            "inp_base_g3",
            "inp_base_g4",
            "inp_base_g5",
            "inp_base_m5",
            "inp_base_m10",
            "inp_base_tax",
            "inp_base_wacc",
            "inp_base_gt",
            "inp_opt_g1",
            "inp_opt_g2",
            "inp_opt_g3",
            "inp_opt_g4",
            "inp_opt_g5",
            "inp_opt_m5",
            "inp_opt_m10",
            "inp_opt_tax",
            "inp_opt_wacc",
            "inp_opt_gt",
            "out_value_ps_pess",
            "out_value_ps_base",
            "out_value_ps_opt",
            "out_value_ps_weighted",
            "out_equity_value_weighted",
            "out_enterprise_value_weighted",
            "out_wacc",
            "out_terminal_g",
            "log_run_id",
            "log_status",
            "log_start_ts",
            "log_end_ts",
            "log_actions_firstrow",
            "log_actions_table",
            "log_assumptions_firstrow",
            "log_assumptions_table",
            "log_story_firstrow",
            "log_story_table",
        ),
    ),
    SkillSpec(
        skill_id="ticker-intake-and-mandate",
        skill_path="skills/ticker-intake-and-mandate",
        phase="intake",
        purpose="Capture mandate, constraints, and high-impact missing inputs.",
        required_tools=("google_sheets",),
        workbook_tabs=("Inputs", "Agent Log"),
        named_ranges=("inp_ticker", "inp_name", "log_run_id", "log_status"),
    ),
    SkillSpec(
        skill_id="sec-filings-and-xbrl-extraction",
        skill_path="skills/sec-filings-and-xbrl-extraction",
        phase="data_collection",
        purpose="Fetch and normalize filing-backed fundamentals with citations.",
        required_tools=("sec_edgar_xbrl", "google_sheets"),
        workbook_tabs=("Inputs", "Sources", "Agent Log"),
        named_ranges=("inp_rev_ttm", "inp_ebit_ttm", "inp_tax_ttm"),
    ),
    SkillSpec(
        skill_id="market-and-fundamentals-harvest",
        skill_path="skills/market-and-fundamentals-harvest",
        phase="data_collection",
        purpose="Ingest market, capital structure, and operating metrics.",
        required_tools=("finnhub_fundamentals", "google_sheets"),
        workbook_tabs=("Inputs", "Dilution (TSM)", "DCF", "Agent Log"),
        named_ranges=(
            "inp_px",
            "inp_cash",
            "inp_debt",
            "inp_basic_shares",
            "inp_tsm_tranche1_count_mm",
            "inp_tsm_tranche1_type",
            "inp_tsm_tranche1_note",
        ),
    ),
    SkillSpec(
        skill_id="rates-and-macro-context",
        skill_path="skills/rates-and-macro-context",
        phase="data_collection",
        purpose="Collect risk-free and macro context for discount-rate assumptions.",
        required_tools=("fred_treasury", "google_sheets"),
        workbook_tabs=("Inputs", "Sources", "Agent Log"),
        named_ranges=("inp_rf", "inp_erp", "inp_beta", "calc_ke", "calc_wacc"),
    ),
    SkillSpec(
        skill_id="transcript-and-guidance-analysis",
        skill_path="skills/transcript-and-guidance-analysis",
        phase="data_collection",
        purpose="Extract guidance and management signals for scenario reasoning.",
        required_tools=("earnings_transcripts", "google_sheets"),
        workbook_tabs=("Story", "Sources", "Agent Log"),
        named_ranges=("log_story_firstrow",),
    ),
    SkillSpec(
        skill_id="corporate-actions-and-cap-table",
        skill_path="skills/corporate-actions-and-cap-table",
        phase="data_collection",
        purpose="Integrate buybacks, splits, and debt/cap-table changes.",
        required_tools=("corporate_actions", "google_sheets"),
        workbook_tabs=("Dilution (TSM)", "Lease Capitalization", "Inputs", "Agent Log"),
        named_ranges=(
            "inp_basic_shares",
            "inp_debt",
            "inp_tsm_tranche1_count_mm",
            "inp_tsm_tranche1_strike",
            "inp_tsm_tranche1_type",
            "inp_tsm_tranche1_note",
            "tsm_tranche_table",
        ),
    ),
    SkillSpec(
        skill_id="peer-set-and-competitive-analysis",
        skill_path="skills/peer-set-and-competitive-analysis",
        phase="validation",
        purpose="Build and justify peers; write competitive context.",
        required_tools=(
            "sector_peer_classification",
            "web_news_search",
            "python_math",
            "google_sheets",
        ),
        workbook_tabs=("Comps", "Story", "Sources", "Agent Log"),
        named_ranges=(
            "comps_target_rev_ttm",
            "comps_target_ebit_ttm",
            "comps_header",
            "comps_firstrow",
            "comps_table",
            "comps_table_full",
            "comps_peer_tickers",
            "comps_peer_names",
            "comps_multiples_header",
            "comps_multiples_values",
            "comps_method_note",
            "comps_peer_count",
            "comps_multiple_count",
            "comps_ev_ebit",
            "comps_ev_sales",
            "comps_pe",
            "comps_notes",
            "sources_table",
            "log_story_firstrow",
        ),
    ),
    SkillSpec(
        skill_id="data-quality-gate-and-normalization",
        skill_path="skills/data-quality-gate-and-normalization",
        phase="data_quality_checks",
        purpose="Validate unit/period consistency and required pre-model inputs before assumptions.",
        required_tools=("google_sheets", "source_contradiction_checker"),
        workbook_tabs=("Inputs", "Sources", "Checks", "Agent Log"),
        named_ranges=(
            "inp_rev_ttm",
            "inp_ebit_ttm",
            "inp_tax_ttm",
            "inp_px",
            "inp_rf",
            "inp_erp",
            "inp_beta",
            "inp_cash",
            "inp_debt",
            "inp_basic_shares",
            "sources_table",
            "checks_statuses",
            "log_actions_firstrow",
            "log_assumptions_firstrow",
            "log_actions_table",
            "log_assumptions_table",
        ),
    ),
    SkillSpec(
        skill_id="assumption-engine-pess-base-opt",
        skill_path="skills/assumption-engine-pess-base-opt",
        phase="assumptions",
        purpose="Set scenario assumptions and scenario weights with rationale.",
        required_tools=("google_sheets", "source_contradiction_checker"),
        workbook_tabs=("Inputs", "Agent Log", "Checks"),
        named_ranges=(
            "inp_pess_g1",
            "inp_base_g1",
            "inp_opt_g1",
            "inp_pess_wacc",
            "inp_base_wacc",
            "inp_opt_wacc",
            "inp_w_pess",
            "inp_w_base",
            "inp_w_opt",
        ),
    ),
    SkillSpec(
        skill_id="sheets-dcf-executor",
        skill_path="skills/sheets-dcf-executor",
        phase="model_run",
        purpose="Execute workbook formulas and read scenario + weighted outputs.",
        required_tools=("google_sheets",),
        workbook_tabs=("DCF", "Output", "Checks", "Agent Log"),
        named_ranges=(
            "out_value_ps_pess",
            "out_value_ps_base",
            "out_value_ps_opt",
            "out_value_ps_weighted",
            "out_equity_value_weighted",
            "out_enterprise_value_weighted",
        ),
    ),
    SkillSpec(
        skill_id="sensitivity-engine",
        skill_path="skills/sensitivity-engine",
        phase="validation",
        purpose="Run and interpret sensitivity grids and stress scenarios.",
        required_tools=("google_sheets",),
        workbook_tabs=("Sensitivity", "Output", "Checks", "Agent Log"),
        named_ranges=(
            "out_wacc",
            "out_terminal_g",
            "sens_base_value_ps",
            "sens_wacc_vector",
            "sens_terminal_g_vector",
            "sens_grid_values",
            "sens_grid_full",
        ),
    ),
    SkillSpec(
        skill_id="story-to-valuation-linker",
        skill_path="skills/story-to-valuation-linker",
        phase="memo",
        purpose="Bind story claims to assumptions and valuation outputs.",
        required_tools=("google_sheets",),
        workbook_tabs=("Story", "Inputs", "Output", "Agent Log"),
        named_ranges=(
            "out_value_ps_weighted",
            "log_story_firstrow",
            "story_thesis",
            "story_growth",
            "story_profitability",
            "story_reinvestment",
            "story_risk",
            "story_sanity_checks",
            "story_grid_header",
            "story_grid_rows",
            "story_grid_citations",
            "story_memo_hooks",
        ),
    ),
    SkillSpec(
        skill_id="citation-and-consistency-auditor",
        skill_path="skills/citation-and-consistency-auditor",
        phase="validation",
        purpose="Enforce numeric grounding and detect source contradictions.",
        required_tools=("source_contradiction_checker", "google_sheets"),
        workbook_tabs=("Sources", "Checks", "Agent Log"),
        named_ranges=(
            "sources_table",
            "log_actions_firstrow",
            "log_actions_table",
            "log_assumptions_firstrow",
            "log_assumptions_table",
        ),
    ),
    SkillSpec(
        skill_id="memo-composer-ib-style",
        skill_path="skills/memo-composer-ib-style",
        phase="memo",
        purpose="Compose final investment memo with scenario framing and citations.",
        required_tools=("llm", "google_sheets"),
        workbook_tabs=("Story", "Comps", "Sensitivity", "Output", "Sources"),
        named_ranges=("out_value_ps_weighted", "out_equity_value_weighted"),
    ),
    SkillSpec(
        skill_id="publish-and-logbook-closeout",
        skill_path="skills/publish-and-logbook-closeout",
        phase="publish",
        purpose="Finalize run status, close logbook, and mark artifact ready.",
        required_tools=("google_sheets",),
        workbook_tabs=("Output", "Agent Log"),
        named_ranges=("log_status", "log_end_ts", "out_run_id"),
    ),
)


def get_skill(skill_id: str) -> SkillSpec:
    """Return a specific skill definition by id."""
    normalized = skill_id.strip().lower()
    for skill in PHASE_V1_SKILLS:
        if skill.skill_id == normalized:
            return skill
    raise KeyError(f"Unknown skill_id: {skill_id}")


def skill_ids() -> tuple[str, ...]:
    """Return all phase-v1 skill identifiers in catalog order."""
    return tuple(skill.skill_id for skill in PHASE_V1_SKILLS)
